import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import numpy as np
import sys
from pathlib import Path


parent_dir = str(Path(__file__).parent.parent)
if parent_dir not in sys.path:
    sys.path.append(parent_dir)
from archtechre_common import *

class CNNFeatureVisualizer:
    def __init__(self, model, unet=None):
        self.model = model
        self.unet = unet
        self.features = []
        self.hook_handles = []

    def _get_hook(self, layer_name):
        def hook(module, input, output):
            # Capture the output of the convolutional layer
            # Shape: [Batch_Size, Channels, Height, Width]
            self.features.append((layer_name, output.detach().cpu()))
        return hook

    def extract_and_return_figure(self, input_batch, true_labels):
        """
        Expects:
        - input_batch: shape [Batch_Size, 3, 224, 224]
        - true_labels: A tensor or list of the real labels for the batch
        - class_names (optional): A list or dict mapping label numbers to string names
        Returns a Matplotlib Figure object.
        """
        # Reset features list for a new batch
        self.features = []
        batch_size = input_batch.shape[0]
        device = next(self.model.parameters()).device
        input_batch = input_batch.to(device)

        # 1. Forward pass through U-Net if provided
        if self.unet is not None:
            self.unet.eval()
            self.unet = self.unet.to(device)
            with torch.no_grad():
                unet_batch = self.unet(input_batch)
        else:
            unet_batch = input_batch

        self.model.eval()

        # 2. Register hooks to all Conv2d layers in the Custom CNN
        # Since your custom CNN defines conv1, conv2, etc., directly on the model,
        # we iterate over named_children() instead of model.features.
        for name, module in self.model.named_children():
            if isinstance(module, nn.Conv2d):
                handle = module.register_forward_hook(self._get_hook(name))
                self.hook_handles.append(handle)

        # 3. Forward pass (triggers hooks AND gets predictions)
        with torch.no_grad():
            outputs = self.model(unet_batch) # Pass unet_batch (or original) to the CNN
            predictions = outputs.argmax(dim=1).cpu()

        # 4. Clean up all hooks
        for handle in self.hook_handles:
            handle.remove()
        self.hook_handles = []

        if isinstance(true_labels, torch.Tensor):
            true_labels = true_labels.cpu().tolist()
        predictions = predictions.tolist()

        # Return the figure generated by the plotting function
        return self._create_batch_figure(
            input_batch.cpu(), 
            unet_batch.detach().cpu(), 
            self.features, 
            true_labels, 
            predictions, 

        )

    def _create_batch_figure(self, input_batch, unet_batch, features, true_labels, predictions):
        batch_size = input_batch.shape[0]
        num_layers = len(features)  # Dynamically adapts to how many Conv2d layers it found
        
        has_unet = self.unet is not None
        base_cols = 2 if has_unet else 1
        num_cols = base_cols + num_layers 
        
        # Make the figure wide enough to hold all columns
        fig, axes = plt.subplots(batch_size, num_cols, figsize=(3 * num_cols, 4 * batch_size))
        
        if batch_size == 1:
            axes = np.expand_dims(axes, axis=0)
            
        for i in range(batch_size):
            # Use the denormalize function defined in your code
            vis_img = denormalize(input_batch[i]).permute(1, 2, 0).numpy()
            
            t_label = true_labels[i]
            p_label = predictions[i]
            
            # Use your get_class_name function
            t_text = get_class_name(t_label) 
            p_text = get_class_name(p_label)
            
            title_color = "green" if t_label == p_label else "red"
            
            col_idx = 0
            
            # Plot 1: Original Input Image
            axes[i, col_idx].imshow(vis_img)
            if has_unet:
                axes[i, col_idx].set_title(f"Original Input\nTrue: {t_text}", fontsize=14)
            else:
                axes[i, col_idx].set_title(f"True: {t_text}\nPred: {p_text}", color=title_color, fontsize=14, fontweight='bold')
            axes[i, col_idx].axis('off')
            col_idx += 1

            # Plot 2 (Conditional): U-Net Preprocessor Output
            if has_unet:
                u_img = unet_batch[i]
                u_min, u_max = u_img.min(), u_img.max()
                unet_vis_img = ((u_img - u_min) / (u_max - u_min + 1e-8)).permute(1, 2, 0).numpy()

                axes[i, col_idx].imshow(unet_vis_img)
                axes[i, col_idx].set_title(f"U-Net Feature Map\nPred: {p_text}", color=title_color, fontsize=14, fontweight='bold')
                axes[i, col_idx].axis('off')
                col_idx += 1
            
            # Plot subsequent columns: The feature maps for this specific image
            for j, (layer_name, feature_tensor) in enumerate(features):
                # Isolate the specific image's feature map: [Channels, Height, Width]
                f_map = feature_tensor[i] 
                
                # Average across all channels to see the overall spatial activation
                f_map_mean = f_map.mean(dim=0).numpy() # Shape: [Height, Width]
                
                # Normalize the heatmap between 0 and 1 for clean plotting
                f_min, f_max = f_map_mean.min(), f_map_mean.max()
                if f_max - f_min > 0:
                    f_map_mean = (f_map_mean - f_min) / (f_max - f_min)
                
                # Plot the feature map (using 'viridis' as it's standard for CNN activations)
                axes[i, col_idx].imshow(f_map_mean, cmap='viridis')
                
                # Only add titles to the top row to keep the plot clean
                if i == 0:
                    axes[i, col_idx].set_title(layer_name, fontsize=12)
                axes[i, col_idx].axis('off')
                
                col_idx += 1
            
        plt.tight_layout()
        return fig