import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import numpy as np
import sys
from pathlib import Path


parent_dir = str(Path(__file__).parent.parent)
if parent_dir not in sys.path:
    sys.path.append(parent_dir)
from archtechre_common import *


class VGG16FeatureVisualizer:
    def __init__(self, model):
        self.model = model
        self.features = []
        self.hook_handles = []

    def _get_hook(self, layer_name):
        def hook(module, input, output):
            # Capture the output of the convolutional layer
            # Shape: [Batch_Size, Channels, Height, Width]
            self.features.append((layer_name, output.detach().cpu()))
        return hook

    def extract_and_return_figure(self, input_batch, true_labels, class_names=None):
        """
        Expects:
        - input_batch: shape [Batch_Size, 3, 224, 224]
        - true_labels: A tensor or list of the real labels for the batch
        - class_names (optional): A list or dict mapping label numbers to string names
        Returns a Matplotlib Figure object.
        """
        # Reset features list for a new batch
        self.features = []
        batch_size = input_batch.shape[0]
        device = next(self.model.parameters()).device
        input_batch = input_batch.to(device)

        self.model.eval()

        # 1. Register hooks to all Conv2d layers in VGG16's feature extractor
        layer_counter = 1
        for name, module in self.model.features.named_children():
            if isinstance(module, nn.Conv2d):
                layer_name = f"Conv_{layer_counter}"
                handle = module.register_forward_hook(self._get_hook(layer_name))
                self.hook_handles.append(handle)
                layer_counter += 1

        # 2. Forward pass (triggers hooks AND gets predictions)
        with torch.no_grad():
            outputs = self.model(input_batch)
            predictions = outputs.argmax(dim=1).cpu()

        # 3. Clean up all hooks
        for handle in self.hook_handles:
            handle.remove()
        self.hook_handles = []

        if isinstance(true_labels, torch.Tensor):
            true_labels = true_labels.cpu().tolist()
        predictions = predictions.tolist()

        # Return the figure generated by the plotting function
        return self._create_batch_figure(input_batch.cpu(), self.features, true_labels, predictions, class_names)

    def _create_batch_figure(self, input_batch, features, true_labels, predictions, class_names):
        batch_size = input_batch.shape[0]
        num_layers = len(features)  # VGG16 has 13 Conv layers
        num_cols = 1 + num_layers   # 1 for input image + 13 for feature maps
        
        # Make the figure wide enough to hold all columns
        fig, axes = plt.subplots(batch_size, num_cols, figsize=(3 * num_cols, 4 * batch_size))
        
        if batch_size == 1:
            axes = np.expand_dims(axes, axis=0)
            
        for i in range(batch_size):
            # Use the denormalize function defined in your code
            vis_img = denormalize(input_batch[i]).permute(1, 2, 0).numpy()
            
            t_label = true_labels[i]
            p_label = predictions[i]
            
            # Use your get_class_name function
            t_text = get_class_name(t_label)
            p_text = get_class_name(p_label) 
            
            title_color = "green" if t_label == p_label else "red"
            
            # Plot 1: Input Image with Truth & Prediction
            axes[i, 0].imshow(vis_img)
            axes[i, 0].set_title(f"True: {t_text}\nPred: {p_text}", color=title_color, fontsize=14, fontweight='bold')
            axes[i, 0].axis('off')
            
            # Plot the feature maps for this specific image
            for j, (layer_name, feature_tensor) in enumerate(features):
                col = j + 1
                
                # Isolate the specific image's feature map: [Channels, Height, Width]
                f_map = feature_tensor[i] 
                
                # Average across all channels to see the overall spatial activation
                f_map_mean = f_map.mean(dim=0).numpy() # Shape: [Height, Width]
                
                # Normalize the heatmap between 0 and 1 for clean plotting
                f_min, f_max = f_map_mean.min(), f_map_mean.max()
                if f_max - f_min > 0:
                    f_map_mean = (f_map_mean - f_min) / (f_max - f_min)
                
                # Plot the feature map (using 'viridis' as it's standard for CNN activations)
                axes[i, col].imshow(f_map_mean, cmap='viridis')
                
                # Only add titles to the top row to keep the plot clean
                if i == 0:
                    axes[i, col].set_title(layer_name, fontsize=12)
                axes[i, col].axis('off')
            
        plt.tight_layout()
        return fig